-- Run as the Oracle application schema owner.  Statements are idempotent.
-- The users table is deliberately not defined here; see README.md.
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE cabins (id VARCHAR2(36) PRIMARY KEY, cabinNumber VARCHAR2(50) UNIQUE NOT NULL, status VARCHAR2(50) DEFAULT 'Available', tariff NUMBER DEFAULT 500, daily_rate NUMBER(10,2) DEFAULT 500, floor NUMBER DEFAULT 1, cabin_type VARCHAR2(20) DEFAULT 'NORMAL_CABIN' CHECK (cabin_type IN ('FREEZER','NORMAL_CABIN')), createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE admin (id VARCHAR2(36) PRIMARY KEY, username VARCHAR2(100) UNIQUE NOT NULL, email VARCHAR2(150), password VARCHAR2(255) NOT NULL, role VARCHAR2(50) DEFAULT 'Admin', status VARCHAR2(50) DEFAULT 'Active', createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE body_types (id VARCHAR2(36) PRIMARY KEY, name VARCHAR2(100) UNIQUE NOT NULL, description CLOB, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE concession_authorities (id VARCHAR2(36) PRIMARY KEY, name VARCHAR2(255) NOT NULL, designation VARCHAR2(255), department VARCHAR2(255), maxDiscountPercent NUMBER DEFAULT 100, isActive NUMBER(1) DEFAULT 1, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE bodies (id VARCHAR2(36) PRIMARY KEY, bodyNumber VARCHAR2(50) UNIQUE NOT NULL, bodyType VARCHAR2(50) NOT NULL, hospitalNumber VARCHAR2(100), patientName VARCHAR2(255), gender VARCHAR2(20), age NUMBER, locality VARCHAR2(255), dateOfDeath VARCHAR2(50), timeOfDeath VARCHAR2(50), declaredBy VARCHAR2(255), reasonOfDeath CLOB, deathIntimationNo VARCHAR2(100), mlcNo VARCHAR2(100), estimatedDaysOfStay NUMBER, witness1Name VARCHAR2(255), witness1Address CLOB, witness1Contact VARCHAR2(50), witness2Name VARCHAR2(255), witness2Address CLOB, witness2Contact VARCHAR2(50), billing_status VARCHAR2(50) DEFAULT 'PENDING', status VARCHAR2(50) DEFAULT 'Registered', createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, policeStationName VARCHAR2(255), stationSiName VARCHAR2(255), presentPoliceOfficerName VARCHAR2(255), nocCertificateUrl CLOB, freezerRequired NUMBER(1) DEFAULT 1)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE cabin_allocations (id VARCHAR2(36) PRIMARY KEY, bodyId VARCHAR2(36) NOT NULL, cabinId VARCHAR2(36) NOT NULL, admissionDateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP, releaseDateTime TIMESTAMP NULL, estimatedReleaseDateTime TIMESTAMP NULL, advanceAmount NUMBER DEFAULT 0, hourlyRate NUMBER DEFAULT 50, minHours NUMBER DEFAULT 4, freeHours NUMBER DEFAULT 0, status VARCHAR2(50) DEFAULT 'Allocated', createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE billing (id VARCHAR2(36) PRIMARY KEY, bodyId VARCHAR2(36) NOT NULL, cabinAllocationId VARCHAR2(36), totalAmount NUMBER DEFAULT 0, discountAmount NUMBER DEFAULT 0, discountReason CLOB, concessionAuthorityId VARCHAR2(36), netAmount NUMBER DEFAULT 0, servicesAmount NUMBER DEFAULT 0, status VARCHAR2(50) DEFAULT 'Pending', settledAt TIMESTAMP NULL, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, firstDayCharge NUMBER(10,2), extraHours NUMBER, hourlyRate NUMBER(10,2), additionalHourCharges NUMBER(10,2), totalHours NUMBER, advanceAmount NUMBER(10,2), staffConcession NUMBER(1) DEFAULT 0, staffName VARCHAR2(255), staffEmployeeId VARCHAR2(100), staffAddress CLOB, staffPhone VARCHAR2(20), staffRelation VARCHAR2(100))
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE billing_services (id VARCHAR2(36) PRIMARY KEY, billingId VARCHAR2(36) NOT NULL, serviceId VARCHAR2(36), serviceName VARCHAR2(255) NOT NULL, amount NUMBER NOT NULL, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE service_billing (id VARCHAR2(36) PRIMARY KEY, bodyId VARCHAR2(36) NOT NULL, billingId VARCHAR2(36), serviceId VARCHAR2(36), serviceName VARCHAR2(255) NOT NULL, serviceAmount NUMBER(10,2) DEFAULT 0 NOT NULL, discountAmount NUMBER(10,2) DEFAULT 0 NOT NULL, netAmount NUMBER(10,2) DEFAULT 0 NOT NULL, status VARCHAR2(50) DEFAULT 'Pending', createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE mortuary_service_master (id VARCHAR2(36) PRIMARY KEY, service_name VARCHAR2(255) NOT NULL, tariff NUMBER(10,2) DEFAULT 0 NOT NULL, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE body_releases (id VARCHAR2(36) PRIMARY KEY, bodyId VARCHAR2(36) NOT NULL, releaseType VARCHAR2(50) NOT NULL, takenBy VARCHAR2(255), relationship VARCHAR2(100), address CLOB, contactNumber VARCHAR2(50), policeStation VARCHAR2(255), siName VARCHAR2(255), nocDocument CLOB, legalDocuments CLOB, releaseDateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE body_documents (id VARCHAR2(36) PRIMARY KEY, bodyId VARCHAR2(36) NOT NULL, fileName VARCHAR2(255) NOT NULL, fileUrl CLOB NOT NULL, createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE housekeeping_tasks (id VARCHAR2(36) PRIMARY KEY, cabinId VARCHAR2(36) NOT NULL, status VARCHAR2(50) DEFAULT 'PENDING', assignedTo VARCHAR2(255), createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE system_settings (id VARCHAR2(36) PRIMARY KEY, first_day_charge NUMBER(10,2) DEFAULT 2100 NOT NULL, hourly_charge_after_24hrs NUMBER(10,2) DEFAULT 130 NOT NULL, updated_by VARCHAR2(255), updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
CREATE OR REPLACE TRIGGER cabins_set_updated_at BEFORE UPDATE ON cabins FOR EACH ROW BEGIN :NEW.updatedAt := CURRENT_TIMESTAMP; END;
/
CREATE OR REPLACE TRIGGER admin_set_updated_at BEFORE UPDATE ON admin FOR EACH ROW BEGIN :NEW.updatedAt := CURRENT_TIMESTAMP; END;
/
CREATE OR REPLACE TRIGGER bodies_set_updated_at BEFORE UPDATE ON bodies FOR EACH ROW BEGIN :NEW.updatedAt := CURRENT_TIMESTAMP; END;
/
CREATE OR REPLACE TRIGGER mort_serv_set_updated_at BEFORE UPDATE ON mortuary_service_master FOR EACH ROW BEGIN :NEW.updatedAt := CURRENT_TIMESTAMP; END;
/
CREATE OR REPLACE TRIGGER housekeeping_set_updated_at BEFORE UPDATE ON housekeeping_tasks FOR EACH ROW BEGIN :NEW.updatedAt := CURRENT_TIMESTAMP; END;
/
CREATE OR REPLACE TRIGGER settings_set_updated_at BEFORE UPDATE ON system_settings FOR EACH ROW BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/
BEGIN EXECUTE IMMEDIATE q'~
CREATE TABLE mortuary_users (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, full_name VARCHAR2(255) NOT NULL, employee_id VARCHAR2(100) UNIQUE NOT NULL, department VARCHAR2(100) NOT NULL, phone1 VARCHAR2(20), phone2 VARCHAR2(20), email VARCHAR2(150) UNIQUE NOT NULL, password VARCHAR2(255) NOT NULL, approval_status VARCHAR2(50) DEFAULT 'pending', admin_remarks VARCHAR2(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
~'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
CREATE OR REPLACE TRIGGER mortuary_users_set_updated_at BEFORE UPDATE ON mortuary_users FOR EACH ROW BEGIN :NEW.updated_at := CURRENT_TIMESTAMP; END;
/

